services:
  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - mynetwork
    env_file:
      - ./backend/.env

  api:
    build: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    networks:
      - mynetwork
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - api
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork: